export component MainWindow inherits Window {
    width: 400px;
    height: 300px;

    VerticalLayout {
        alignment: center;

        Text {
            text: "Hello Slint w Wasm!";
            color: green;
            font-size: 24px;
        }

        Text {
            text: "Projekt działa w przeglądarce!";
            color: #666;
        }

        Text {
            text: "Updated second time";
            color: #000000;
        }
    }
}