import { ScrollView } from "std-widgets.slint";

export component MainWindow inherits Window {
    in-out property <string> json_data;
    width: 910px;
    VerticalLayout {
        ScrollView {
            vertical-stretch: 1;
            vertical-scrollbar-policy: always-on;
                        
            VerticalLayout {
                padding: 5px;

                Text {
                    text: json_data;
                    color: #000000;
                    wrap: word-wrap;
                    min-height: self.preferred-height; 
                }
            }
        }
    }
}